#
# Makefile for the touchscreen drivers.
#

include $(srctree)/drivers/misc/mediatek/Makefile.custom
ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/

obj-y += lgtp_device_mit200.o
obj-y += lgtp_melfas_fw_upgrade.o
