#gt915 touchpanel driver


obj-$(CONFIG_GT9157_TOUCHPANEL_DRIVER)	+= gt9157.o
#gt915 update file
obj-$(CONFIG_GT9157_TOUCHPANEL_UPDATE)	+= gt9157_update.o
#debug tool
obj-$(CONFIG_GT9157_TOUCHPANEL_DEBUG)	+= goodix_tool.o
