#
# Makefile for the TD4191 drivers.
#

# Each configuration option enables a list of files.
obj-$(CONFIG_TOUCHSCREEN_LGE_SYNAPTICS_TD4191) += lge_touch_core.o
obj-$(CONFIG_TOUCHSCREEN_LGE_SYNAPTICS_TD4191) += touch_synaptics.o
obj-$(CONFIG_TOUCHSCREEN_LGE_SYNAPTICS_TD4191) += touch_synaptics_ds5_fw_upgrade.o
#obj-$(CONFIG_TOUCHSCREEN_SYNAPTICS_TD4191) += touch_synaptics_proximity.o
obj-$(CONFIG_TOUCHSCREEN_LGE_SYNAPTICS_TD4191) += touch_synaptics_rmi_dev.o
obj-$(CONFIG_TOUCHSCREEN_LGE_SYNAPTICS_TD4191) += DS5/
#obj-$(CONFIG_TOUCHSCREEN_SYNAPTICS_I2C_RMI4)		+= synaptics_i2c_rmi4.o
#obj-$(CONFIG_TOUCHSCREEN_SYNAPTICS_DSX_RMI4_DEV)	+= synaptics_rmi_dev.o
#obj-$(CONFIG_TOUCHSCREEN_SYNAPTICS_DSX_FW_UPDATE) 	+= synaptics_fw_update.o
obj-$(CONFIG_TOUCHSCREEN_SYNAPTICS_TD4191_DSX) += synaptics_dsx/
