#GT928 touchpanel driver

#obj-$(CONFIG_TOUCHSCREEN_GT928)         += gt928.o
obj-y         += gt928.o
obj-y         += gt928_asus.o
obj-y         += gt928_tool.o
obj-y         += gt928_update.o
obj-y         += gt928_openshort.o