#[PLATFORM]-Add-BEGIN by TCTNB.ZXZ, FR-788074, 2014/09/20 add msg2633 TP
obj-$(CONFIG_TOUCHSCREEN_MSG) += mstar_drv_common.o
obj-$(CONFIG_TOUCHSCREEN_MSG) += mstar_drv_ic_fw_porting_layer.o
obj-$(CONFIG_TOUCHSCREEN_MSG) += mstar_drv_main.o
obj-$(CONFIG_TOUCHSCREEN_MSG) += mstar_drv_mutual_fw_control.o
obj-$(CONFIG_TOUCHSCREEN_MSG) += mstar_drv_mutual_mp_test.o
obj-$(CONFIG_TOUCHSCREEN_MSG) += mstar_drv_platform_interface.o
obj-$(CONFIG_TOUCHSCREEN_MSG) += mstar_drv_platform_porting_layer.o
obj-$(CONFIG_TOUCHSCREEN_MSG) += mstar_drv_qcom.o
obj-$(CONFIG_TOUCHSCREEN_MSG) += mstar_drv_utility_adaption.o
#obj-$(CONFIG_TOUCHSCREEN_MSG) += mstar_drv_self_fw_control.o
#obj-$(CONFIG_TOUCHSCREEN_MSG) += mstar_drv_self_mp_test.o
#[PLATFORM]-Add-End by TCTNB.ZXZ