#/* < DTS2014041705903 zhangmin 20140418 begin */
#
# Makefile for device detect devices
#
obj-$(CONFIG_HUAWEI_HW_DEV_DCT) += hw_dev_dec.o

#/* DTS2014041705903 zhangmin 20140418 end > */
#/* < DTS2015051206005 chendong cwx241705 begin */
obj-$(CONFIG_HUAWEI_HW_SIM_DETECT) += hw_sim_detect.o
#/*  DTS2015051206005 chendong cwx241705 end > */
