#
# Makefile for MELFAS MIP4 Touchscreen driver
#

obj-$(CONFIG_TOUCHSCREEN_MELFAS_MIT300)	+= lge_ts_core.o lge_ts_melfas.o lge_ts_mit300.o
obj-$(CONFIG_TOUCHSCREEN_MELFAS_MIT300_PH1)	+= lge_ts_core.o lge_ts_melfas.o lge_ts_mit300.o
