# Switch Class Driver
obj-$(CONFIG_SWITCH)		+= switch_class.o
obj-$(CONFIG_SWITCH_GPIO)	+= switch_gpio.o
obj-$(CONFIG_SWITCH_HALL)	+= switch_hall.o
obj-$(CONFIG_BBK_SWITCH_GSENSOR_INT1)	+= switch_gsensor_int1.o
