#
# Makefile for sensor chip drivers.
#

obj-$(CONFIG_SENSORS_BMC156)    += bmc156/
obj-$(CONFIG_SENSORS_AL3320)	+= al3320/
obj-$(CONFIG_SENSORS_CM36686)	+= cm36686/
obj-$(CONFIG_SENSORS_HALL)   	+= hall/

