#FT6336 touchpanel driver


obj-$(CONFIG_FT6336_TOUCHPANEL_DRIVER)	+= ft6x06_ts.o
#update file
obj-$(CONFIG_FT6336_TOUCHPANEL_UPDATE)	+= ft6x06_ex_fun.o
#debug tool
obj-$(CONFIG_FT6336_TOUCHPANEL_DEBUG)	+= focaltech_ctl.o
