#[PLATFORM]-Add-BEGIN by TCTSH.furong, 2014/11/18 add msg2638 TP
obj-$(CONFIG_TOUCHSCREEN_MSG2638) += mstar_drv_common.o
obj-$(CONFIG_TOUCHSCREEN_MSG2638) += mstar_drv_ic_fw_porting_layer.o
obj-$(CONFIG_TOUCHSCREEN_MSG2638) += mstar_drv_main.o
obj-$(CONFIG_TOUCHSCREEN_MSG2638) += mstar_drv_mutual_fw_control.o
obj-$(CONFIG_TOUCHSCREEN_MSG2638) += mstar_drv_mutual_mp_test.o
obj-$(CONFIG_TOUCHSCREEN_MSG2638) += mstar_drv_platform_interface.o
obj-$(CONFIG_TOUCHSCREEN_MSG2638) += mstar_drv_platform_porting_layer.o
obj-$(CONFIG_TOUCHSCREEN_MSG2638) += mstar_drv_qcom.o
obj-$(CONFIG_TOUCHSCREEN_MSG2638) += mstar_drv_utility_adaption.o
#obj-$(CONFIG_TOUCHSCREEN_MSG) += mstar_drv_self_fw_control.o
#obj-$(CONFIG_TOUCHSCREEN_MSG) += mstar_drv_self_mp_test.o
#[PLATFORM]-Add-End by TCTSH.furong
