#
# Makefile for the input misc drivers.
#

# Each configuration option enables a list of files.


obj-$(CONFIG_BBK_SENSORS_APDS9920)	+= apds9920.o
obj-$(CONFIG_BBK_SENSORS_APDS9960)	+= apds9960.o
obj-$(CONFIG_BBK_SENSORS_APDS9922)	+= apds9922.o
obj-$(CONFIG_BBK_SENSORS_GP2AP008T)  += gp2ap008t.o
obj-$(CONFIG_BBK_SENSORS_GYRO_L3GD20TR)	+= l3gd20_gyr.o
obj-$(CONFIG_BBK_SENSORS_MAG_YAS533)	+= yas_mag_drv-yas532.o yas_mag_kernel.o
obj-$(CONFIG_BBK_SENSORS_MAG_YAS537)	+= yas_mag_kernel537.o
obj-$(CONFIG_BBK_SENSORS_LIS3DH)		+= lis3dh_acc.o
obj-$(CONFIG_BBK_SENSORS_LSM330ACC)+= lsm330_acc.o
obj-$(CONFIG_BBK_SENSORS_LSM330GYRO)+= lsm330_gyr.o
obj-$(CONFIG_BBK_SENSORS_TMD277X)		+= tmd2771.o
obj-$(CONFIG_BBK_SENSORS_MAG_AKM8963)		+= akm8963.o
obj-$(CONFIG_BBK_SENSORS_MAG_AKM09911)		+= akm09911.o
obj-$(CONFIG_BBK_SENSORS_MAG_ALPS007)		+= hscdtd007a.o
obj-$(CONFIG_BBK_SENSORS_KX023)		+= kx023_acc.o
obj-$(CONFIG_BBK_SENSORS_MPU6500)		+= mpu6500.o
obj-y += vivo_logger.o
obj-y += interface.o
obj-y += config/
obj-y += across.o
