#
# Makefile for MELFAS MIP4 Touchscreen driver
#

obj-$(CONFIG_TOUCHSCREEN_MELFAS_MMS438_REFERENCE)         += mip4.o mip4_mod.o mip4_debug.o mip4_fw_mms438.o mip4_lge.o
obj-$(CONFIG_TOUCHSCREEN_MELFAS_MMS449_REFERENCE)         += mip4.o mip4_mod.o mip4_debug.o mip4_fw_mms438.o mip4_lge.o
obj-$(CONFIG_TOUCHSCREEN_MELFAS_MMS458_REFERENCE)         += mip4.o mip4_mod.o mip4_debug.o mip4_fw_mms438.o mip4_lge.o
obj-$(CONFIG_TOUCHSCREEN_MELFAS_MMS500_REFERENCE)         += mip4.o mip4_mod.o mip4_debug.o mip4_fw_mms500.o mip4_lge.o
obj-$(CONFIG_TOUCHSCREEN_MELFAS_MCS8040L_REFERENCE)       += mip4.o mip4_mod.o mip4_debug.o mip4_fw_mcs8040l.o mip4_lge.o
obj-$(CONFIG_TOUCHSCREEN_MELFAS_MIT200_REFERENCE)         += mip4.o mip4_mod.o mip4_debug.o mip4_fw_mit200.o mip4_lge.o
obj-$(CONFIG_TOUCHSCREEN_MELFAS_MIT300_REFERENCE)         += mip4.o mip4_mod.o mip4_debug.o mip4_fw_mit300.o mip4_lge.o

