ccflags-y += -Idrivers/media/platform/msm/camera_v2
ccflags-y += -Idrivers/media/platform/msm/camera_v2/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2/sensor/cci
ccflags-y += -Idrivers/media/platform/msm/camera_v2/sensor/laser_focus_zc550kl
ccflags-y += -Idrivers/media/platform/msm/camera_v2/sensor/laser_focus_zc550kl/vl6180_api/inc

obj-$(CONFIG_MSMB_CAMERA) += msm_laser_focus_vl6180_api.o
obj-$(CONFIG_MSMB_CAMERA) += vl6180x_i2c.o
obj-$(CONFIG_MSMB_CAMERA) += vl6180x_api.o
obj-$(CONFIG_MSMB_CAMERA) += kernel_driver_timer.o 
