ccflags-y += -Idrivers/media/platform/msm/camera_v2
ccflags-y += -Idrivers/media/platform/msm/camera_v2/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2/sensor/cci

#obj-$(CONFIG_MSMB_CAMERA) += msm_laser_focus_vl6180.o
#obj-$(CONFIG_MSMB_CAMERA) += msm_laser_focus_hepta.o
obj-$(CONFIG_MSMB_CAMERA) += sysfs/
obj-$(CONFIG_MSMB_CAMERA) += vl6180_api/
