#msg21xx touchpanel driver
# modify(add) by junfeng.zhou.sz for [TP driver development (1st source)] with PR721418 begin . 20140714 
obj-$(CONFIG_TOUCHSCREEN_MSG21XX) += msg2138.o
# modify(add) by junfeng.zhou.sz for [TP driver development (1st source)] with PR721418 end .
